package essentials;

import config.configuration;

public class indexEssentials {

    private static String header() {
        String str = "";
        str += "<!DOCTYPE html>\n"
                + "<html>\n"
                + "    <head>\n"
                + "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                + "        <title>" + configuration.TITLE + "</title>\n"
                + "        <link href=" + configuration.STYLES + "index.css rel=\"stylesheet\" type=\"text/css\"/>\n"
                + "        <script src=" + configuration.JQUERY + " type=\"text/javascript\"></script>\n"
                + "        <link href=" + configuration.FONTS + " rel=\"stylesheet\" type=\"text/css\"/>\n"
                + "    </head>\n"
                + "    <body>\n"
                + "    <main class=\"container\">";
        return str;
    }

    private static String topNav() {
        String str = "";
        str += "      <div class=\"Navigation\">\n"
                + "            <div class=\"column-offset-0 column-3\">\n"
                + "                <div class=\"row\">\n"
                + "                    <!--<img src=\"images/logo.png\" class=\"img-fluid\">-->\n"
                + "                    <h1 style='padding:50px 10px'>Secure <span>Line</span></h1>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            <div class=\"column-offset-1 column-7\">\n"
                + "                <div class=\"row mainNav\">\n"
                + "                    <div class=\"column-4\">\n"
                + "                        <div class=\"row\">\n"
                + "                            <div class=\"column-3\">\n"
                + "                                <div class=\"icon\">\n"
                + "                                    <i class=\"fa fa-phone\"></i>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                            <div class=\"column-9\">\n"
                + "                                <strong>Call Now</strong>\n"
                + "                                <small>(+121)1800 123 456</small>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                    <div class=\"column-4\">\n"
                + "                        <div class=\"row\">\n"
                + "                            <div class=\"column-3\">\n"
                + "                                <div class=\"icon\">\n"
                + "                                    <i class=\"fa fa-envelope-o\"></i>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                            <div class=\"column-9\">\n"
                + "                                <strong>Send Message</strong>\n"
                + "                                <small>support@development.com</small>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                    <div class=\"column-4\">\n"
                + "                        <div class=\"row\">\n"
                + "                            <div class=\"column-3\">\n"
                + "                                <div class=\"icon\">\n"
                + "                                    <i class=\"fa fa-map-marker\"></i>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                            <div class=\"column-9\">\n"
                + "                                <strong>Our Location</strong>\n"
                + "                                <small>Lal Chowk,Srinagar</small>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "        </div>";
        return str;
    }

    private static String mainNav() {
        String str = "";
        str += "     <div class=\"row main-nav\">\n"
                + "            <div class=\"column-offset-1 column-9\">\n"
                + "                <ul>\n"
                + "                    <li class=\"active\">\n"
                + "                        <a class=\"home\" href=\"wellcome.jsp\">\n"
                + "                            <i class=\"fa fa-home\"></i>\n"
                + "                            Home\n"
                + "                        </a>\n"
                + "                    </li>\n"
                + "                    <li class=\"has-dropdown\">\n"
                + "                        <a href=\"#\">\n"
                + "                            About \n"
                + "                            <i class=\"fa fa-angle-down\"></i>\n"
                + "                        </a>\n"
                + "                        <ul class=\"dropdown\">\n"
                + "                            <li>\n"
                + "                                <a href=\"#\">\n"
                + "                                    About \n"
                + "                                </a>\n"
                + "                            </li>\n"
                + "                            <li>\n"
                + "                                <a href=\"#\">\n"
                + "                                    About \n"
                + "                                </a>\n"
                + "                            </li>\n"
                + "                        </ul>\n"
                + "                    </li>\n"
                + "                    <li class=\"has-dropdown\">\n"
                + "                        <a href=\"contact.jsp\">\n"
                + "                            Contact Us\n"
                + "                        </a>\n"
                + "                    </li>\n"
                + "                </ul>\n"
                + "            </div>\n"
                + "            <div class=\"column-2\">	\n"
                + "            </div>\n"
                + "        </div>";
        return str;
    }

    public static String footer() {
        String str = "";
        str += "<div class=\"row siteFooter\">\n"
                + "            <div class=\"column-offset-1 column-3\">\n"
                + "                <div class=\"companyDiv\">\n"
                + "                    <h3>Company Bio</h3>\n"
                + "                    <div>\n"
                + "                        <p>\n"
                + "                            We are a team of college students working on this project like it's\n"
                + "                            our full time job. Any amount would help support and continue development on this project\n"
                + "                            and is greatly appreciated.\n"
                + "                        </p>\n"
                + "                    </div>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            <div class=\"column-offset-1 column-3\">\n"
                + "                <div class=\"settingDiv\">\n"
                + "                    <h3>Settings</h3>\n"
                + "                    <ul>\n"
                + "                        <li>\n"
                + "                            <i id=\"fb\" class=\"fa fa-facebook\"></i>\n"
                + "                            <a href=\"#\">Facebook</a></br>\n"
                + "                        </li>\n"
                + "                        <li>\n"
                + "                            <i id=\"inst\" class=\"fa fa-instagram\"></i>\n"
                + "                            <a href=\"#\">Instagram</a></br>\n"
                + "                        </li>\n"
                + "                        <li>\n"
                + "                            <i id=\"wap\" class=\"fa fa-whatsapp\"></i>\n"
                + "                            <a href=\"#\">WhatsApp</a></br>\n"
                + "                        </li>\n"
                + "                        <li>\n"
                + "                            <i id=\"twt\" class=\"fa fa-twitter\"></i>\n"
                + "                            <a href=\"#\">Twitter</a></br>\n"
                + "                        </li>\n"
                + "                    </ul>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            <div class=\"column-3\">\n"
                + "                <div class=\"contactDiv\">\n"
                + "                    <h3>Contact Us</h3>\n"
                + "                    <ul>\n"
                + "                        <li>\n"
                + "                            <i class=\"fa fa-phone\"></i>\n"
                + "                            <a href=\"#\">9541279583</a>\n"
                + "                        </li>\n"
                + "                        <li>\n"
                + "                            <i class=\"fa fa-phone\"></i>\n"
                + "                            <a href=\"#\">9541279583</a>\n"
                + "                        </li>\n"
                + "                        <li>\n"
                + "                            <i class=\"fa fa-phone\"></i>\n"
                + "                            <a href=\"#\">9541279583</a>\n"
                + "                        </li>\n"
                + "                        <li>\n"
                + "                            <i class=\"fa fa-phone\"></i>\n"
                + "                            <a href=\"#\">9541279583</a>\n"
                + "                        </li>\n"
                + "                    </ul>\n"
                + "                </div>\n"
                + "            </div> \n"
                + "        </div>\n"
                + "        <div class=\"copyRightDiv\">\n"
                + "            <p>CopyRight &copy 2020 >> Secure Line</p>\n"
                + "        </div>\n"
                + "    </main>\n"
                + "</body>\n"
                + "<script src="+configuration.SCRIPTS+"default.js type=\"text/javascript\"></script>"
                + "</html>";
        return str;
    }
    
     public static String getPage() {
        String str = "";
        str += header();
        str += topNav();
        str += mainNav();
        return str;
    }
}
